@echo off
del /q build.log 2>nul:
del /q setup\*.exe 2>nul:
for /d /r %%i in (*.*) do if exist "%%i\ipch\"    rd /s /q "%%i\ipch\"    && echo Cleaning %%i\ipch\...
for /d /r %%i in (*.*) do if exist "%%i\Debug\"   rd /s /q "%%i\Debug\"   && echo Cleaning %%i\Debug\...
for /d /r %%i in (*.*) do if exist "%%i\Release\" rd /s /q "%%i\Release\" && echo Cleaning %%i\Release\...
for /d /r %%i in (*.*) do if exist "%%i\Win32\"   rd /s /q "%%i\Win32\"   && echo Cleaning %%i\Win32\...
for /d /r %%i in (*.*) do if exist "%%i\x64\"     rd /s /q "%%i\x64\"     && echo Cleaning %%i\x64\...
for /r %%i in (*.po_)  do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.trg)  do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.aps)  do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.ncb)  do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.sdf)  do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.ipch) do del /q "%%i" && echo Cleaning %%i...
if exist ".\ipch\"    rd /s /q ".\ipch\"    && echo Cleaning .\ipch\...
if exist ".\Debug\"   rd /s /q ".\Debug\"   && echo Cleaning .\Debug\...
if exist ".\Release\" rd /s /q ".\Release\" && echo Cleaning .\Release\...
if exist ".\Win32\"   rd /s /q ".\Win32\"   && echo Cleaning .\Win32\...
if exist ".\x64\"     rd /s /q ".\x64\"     && echo Cleaning .\x64\...
